version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    container_name: psicotecnicodb
    volumes:
      - ./postgres:/var/lib/postgresql/data